modLoader="javafml"
loaderVersion="[43,)"
license="The MIT License (MIT)"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="mcp_for_llm"
version="${file.jarVersion}"
displayName="MCP for LLM minecraft"
displayURL="https://example.com"
#credits=""
authors="yymod"
description='''
Expose a local MCP-style server to run Minecraft commands and control the client.
'''

[[dependencies.mcp_for_llm]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcp_for_llm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

